### ISSUE TITLE
Works fine for develo magic lan ethernet adapters but not for Wifi

### ISSUE THREAD

**Issue by mrhell69** [gebi/devolo-cli#1]
Hi

first of all thx for the utility ;-)

I have:

1 x Magic 2 LAN 1-1
2 x Magic 2 LAN triple

for this adapters it works but not for:

Magic 2 WiFi next

Is it more complicated?

KR Gerd

**Comment by mrhell69** [comment]
> 

Good would be to give a password to identiyfy not to leave connectors without password.

**Comment by gebi** [comment]
thx :), i only needed this tool because throughput wity my devolo adapters reguarly locks up and needs a reboot of one of the adapters after which it works again without issues, until the next lock up.

yea, i might be able to add a password if necessary, but no guarantee when.

as for your "Magic 2 WiFi next" adapter, if you give me a HAR dump of you clicking on the reboot button in the web-interface i can add it if it's not completely different ;)

i have a small watchdog running to reboot the adapter like:

`while true; do ping -q 192.168.0.1 -c 3 -W 5 &>/dev/null || (echo -n "### Reboot - "; date; devolo-cli reboot 192.168.0.17; sleep 30); sleep 3 || break; done`

**Comment by mrhell69** [comment]
Hello Gebi,

thx for your fast feedback. My Develo's are almost stable. But I prefer a reboot after forced disconnect in the night (all24 hours).
But your watchdog is also good to have. I took a HAR dump of the reboot (not really sure if I did correctly). Thanks so much!!!
Here is the link to to HAR Dump:
[https://mrhell69.duckdns.org/index.php/s/Ki3ezG6LqQ3ELJp](url)

KR Gerd

**Comment by gebi** [comment]
@mrhell69 sry, but i only get 'ERR_NAME_NOT_RESOLVED' seems your dyndns dropped ;)

**Comment by mrhell69** [comment]
Sorry,

here again:
[https://mrhell69.duckdns.org/index.php/s/Ki3ezG6LqQ3ELJp](url)

**Comment by gebi** [comment]
Sry, your DNS still does not resolve...

**Comment by mrhell69** [comment]
[192.168.178.20.har.log](https://github.com/gebi/devolo-cli/files/10329397/192.168.178.20.har.log) tried on my Phone and DNS works. But Here direkt Upload. KR

**Comment by gebi** [comment]
sry, but 192.168. is your lokal address, that's not working on the
internet, can you not just upload it to eg. https://wetransfer.com/ ?

if you want to encrypt it, my age <https://github.com/FiloSottile/age>
public key is age1zhg34temvuygpqvyj0lteeuyxfnuf9j3p8f55epeagp2ekq63vasxuwajy

**Comment by mrhell69** [comment]
Its the file Name lol:
![Download](https://user-images.githubusercontent.com/1835311/210249101-936a21fe-76e7-4e59-a7ad-bf65dc01dec4.jpg)

**Comment by mrhell69** [comment]
Here on wetransfer:
https://we.tl/t-a6qYNoV5jJ

**Comment by gebi** [comment]
awesome thx, worked :)!

**Comment by gebi** [comment]
hm... i think i found the reboot part in the har dump, but that's a completely different protocol, they are using json-rpc to `/ubus` like

1. `system.management(reboot)`
2. `while true; do login(username: ping, password: "")` to check for the reboot
3. `login(username: root, password: ?` after first sucessfull answer to 2.

as i've no test device and it's a completely different api i don't think i can add this feature alone, but if you want to send a PR :)?

A first hack that might do a reboot on your device should look similarly to this:

```python
#!/usr/bin/env python3

import requests
import json
import uuid


def main():
    url = "http://192.168.176.20/ubus"
    #url = "http://127.0.0.1:4242/ubus"

    # get ubus session id
    payload = {
        "method": "call",
        "params": [ "0"*32, "session", "login", {"username": "root", "password": "", "timeout": 900}],
        "jsonrpc": "2.0",
        "id": str(uuid.uuid4()),
    }
    response = requests.post(url, json=payload).json()
    ret_resultcode, ret_result = response['result']
    ubus_rpc_session = ret_result['ubus_rpc_session']
    print("extracted ubus_rpc_session: ", ubus_rpc_session)

    # reboot
    payload = {
        "method": "call",
        "params": [ ubus_rpc_session, "system.management", "reboot", {}],
        "jsonrpc": "2.0",
        "id": str(uuid.uuid4()),
    }
    response = requests.post(url, json=payload).json()
    print(response)

if __name__ == "__main__":
    main()
```

screenshot from reboot in har dump

![gkrellShoot_01-03-23_114435](https://user-images.githubusercontent.com/659/210343502-4bda1f04-20ae-4373-a320-0b9b55f784b5.jpg)

**Comment by gebi** [comment]
btw, i tried cleaning up your har files as it looks like it contains your wifi pw beside other informations, sry for the inconvenience

**Comment by mrhell69** [comment]
@gebi I wrote you a message on mgebetsroither@mgit.at from Microsoft Teams. Mybe we can have a short session? I tried your code but script was hanging (and did nothing). Sorry unfortunately i don't know python. Or can I sent you some debugging?

KR Gerd

**Comment by gebi** [comment]
sry, that's currently not possible, but it seems it's just an openwrt based ubus over http https://openwrt.org/docs/techref/ubus#access_to_ubus_over_http so i can find something to test on when i have the time.

**Comment by mrhell69** [comment]
Don't worry @gebi , when you have time😉

**Comment by mrhell69** [comment]
Hello Gebi,

problem solved! Using https://github.com/2Fake/devolo_plc_api.

Reboot with password Magic LAN Wifi possible.

Thx for your help
