### ISSUE TITLE
support password protection

### ISSUE THREAD

**Issue by gebi** [gebi/devolo-cli#2]
request from #1 

i'm currently short on time, PR welcome

**Comment by mrhell69** [comment]
Hello Gebi,

problem solved! Using https://github.com/2Fake/devolo_plc_api.

Reboot with password is possible.

Thx for your help

**Comment by gebi** [comment]
awesome thx :)
i notified devolo that they published all their protobuf descriptions in their lib anyway, so no need to "hide" it, nice to finally see them officially publishing them!
